# Generated by Django 4.2 on 2023-05-04 05:47

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('text_news', models.TextField(db_column='text_news')),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('pe_ratio', models.DecimalField(db_column='P/E ratio', decimal_places=2, max_digits=6, null=True)),
                ('mkt_cap', models.DecimalField(db_column='mkt_cap', decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('symbol', models.CharField(db_column='symbol', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z\\d]+$')])),
                ('date', models.DateField(db_column='date')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('eps', models.DecimalField(db_column='eps', decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(db_column='revenue', decimal_places=2, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stocks_app.stock')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
        migrations.CreateModel(
            name='News_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(db_column='sentiment', max_length=256)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.news')),
                ('sector', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks_app.sector')),
                ('stocks', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks_app.stock')),
            ],
            options={
                'db_table': 'news_analysis',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='sector',
            field=models.ManyToManyField(through='stocks_app.News_Analysis', to='stocks_app.sector'),
        ),
        migrations.AddField(
            model_name='news',
            name='stocks',
            field=models.ManyToManyField(through='stocks_app.News_Analysis', to='stocks_app.stock'),
        ),
        migrations.CreateModel(
            name='FavoriteStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stocks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'favorite_stocks',
            },
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_day', models.DateField(db_column='x_day')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('yield_year', models.DecimalField(db_column='yield_year', decimal_places=2, max_digits=6)),
                ('date_of_payment', models.DateField(db_column='date_of_payment')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stocks_app.stock')),
            ],
            options={
                'db_table': 'dividend',
            },
        ),
    ]
