# Generated by Django 4.2 on 2023-04-27 16:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('pe_ratio', models.DecimalField(db_column='P/E ratio', decimal_places=2, max_digits=6, null=True)),
                ('mkt_cap', models.DecimalField(db_column='mkt_cap', decimal_places=2, max_digits=10)),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('symbol', models.CharField(db_column='symbol', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Z\\d]+$')])),
                ('date', models.DateField(db_column='date')),
            ],
            options={
                'db_table': 'stocks',
            },
        ),
    ]
