# Generated by Django 4.2 on 2023-05-15 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='mkt_cap',
            field=models.DecimalField(db_column='mkt_cap', decimal_places=2, max_digits=18),
        ),
    ]
