# Generated by Django 4.2 on 2023-04-27 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_day', models.DateField(db_column='x_day')),
                ('price', models.DecimalField(db_column='price', decimal_places=2, max_digits=10)),
                ('yield_year', models.DecimalField(db_column='yield_year', decimal_places=2, max_digits=6)),
                ('date_of_payment', models.DateField(db_column='date_of_payment')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stocks_app.stock')),
            ],
            options={
                'db_table': 'dividend',
            },
        ),
    ]
