# Generated by Django 4.2 on 2023-05-04 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news_analysis',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks_app.sector'),
        ),
        migrations.AlterField(
            model_name='news_analysis',
            name='stocks',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stocks_app.stock'),
        ),
        migrations.AlterField(
            model_name='stock',
            name='pe_ratio',
            field=models.DecimalField(blank=True, db_column='P/E ratio', decimal_places=2, max_digits=6, null=True),
        ),
    ]
