# Generated by Django 4.2 on 2023-04-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0002_dividend'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=256)),
                ('email', models.EmailField(db_column='email', max_length=100, unique=True)),
                ('password', models.CharField(db_column='password', max_length=256)),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
