# Generated by Django 4.2 on 2023-04-27 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(db_column='name', max_length=100),
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='FavoriteStocks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_marked', models.BooleanField(db_column='is_marked', default=False)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.stock')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.user')),
            ],
            options={
                'db_table': 'favorite stocks',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='stock',
            field=models.ManyToManyField(through='stocks_app.FavoriteStocks', to='stocks_app.stock'),
        ),
    ]
