# Generated by Django 4.2 on 2023-05-29 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0003_alter_stock_pe_ratio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='favoritestocks',
            old_name='stocks',
            new_name='stock',
        ),
    ]
