# Generated by Django 4.2 on 2023-04-27 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0004_alter_user_name_alter_user_table_favoritestocks_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='name', max_length=100)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stocks_app.stock')),
            ],
            options={
                'db_table': 'sector',
            },
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date')),
                ('eps', models.DecimalField(db_column='eps', decimal_places=2, max_digits=10)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='stocks_app.stock')),
            ],
            options={
                'db_table': 'reports',
            },
        ),
    ]
