# Generated by Django 4.2 on 2023-06-19 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0005_alter_reports_eps'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='revenue',
            field=models.DecimalField(db_column='revenue', decimal_places=2, max_digits=20),
        ),
    ]
