# Generated by Django 4.2 on 2023-04-27 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks_app', '0005_sector_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_column='date', null=True)),
                ('text_news', models.TextField(db_column='text_news', null=True)),
            ],
            options={
                'db_table': 'news',
            },
        ),
        migrations.RemoveField(
            model_name='sector',
            name='stock',
        ),
        migrations.CreateModel(
            name='News_Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sentiment', models.CharField(db_column='sentiment', max_length=256)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.news')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.sector')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stocks_app.stock')),
            ],
            options={
                'db_table': 'news_analysis',
            },
        ),
        migrations.AddField(
            model_name='news',
            name='sector',
            field=models.ManyToManyField(through='stocks_app.News_Analysis', to='stocks_app.stock'),
        ),
        migrations.AddField(
            model_name='sector',
            name='stock',
            field=models.ManyToManyField(through='stocks_app.News_Analysis', to='stocks_app.stock'),
        ),
    ]
